# -*- mode: ruby -*-
# vi: set ft=ruby :

### Includes dependencies to build riak-extl

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end
  config.vm.provision "shell", inline: <<-SHELL
    wget https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
    sudo dpkg -i erlang-solutions_1.0_all.deb
    sudo apt-get update
    sudo apt-get -y install esl-erlang=1:17.5 elixir=1.0.4-1 git
  SHELL
end
